blog/urls.py
# -*- coding: UTF-8 -*-
'''
=================================================
@Project -> File   ：myblog -> urls.py
@IDE    ：PyCharm
@Author ：XuMou
@Date   ：2020/7/6 16:21
==================================================
'''

from django.urls import path, re_path
from blog import views
from django.views.static import serve
from myblog import settings
import debug_toolbar
from stark.service.site import site
urlpatterns = [
    path("", views.index),
    path("login/", views.login),
    path("index/", views.index),
    re_path('^$', views.index),  #
    path("register/", views.register),
    # 修改密码
    path('change_pwd/', views.change_pwd),

    # 账户注销
    path("logout/", views.logout),

    # media 配置
    re_path(r"media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),

    # 个人站点url
    # ?P<value1>为组名，可根据组名定位匹配值的位置， 注意：是在.group()中的标记
    #  ?P<value>的意思就是命名一个名字为value的组，匹配规则符合后面的/w+
    # re_path(r'^test/$',views.test),
    # re_path(r'^(?P<username>\w+)/$', views.home_site),
    # 个人站点基于 当前用户的 的站点
    re_path(r'^(?P<username>\w+)/(?P<condition>tag|category|archive>)/(?P<param>.*)/$', views.home_site),
    # 文章详情页面的实现 ，登陆用户
    re_path(r'^(?P<username>\w+)/articles/(?P<article_id>\d+)/$', views.user_article_detail),
    # 未登录用户
    re_path(r'^articles/(?P<article_id>\d+)/$', views.article_detail),

    # 点赞视图url
    path(r'digg/', views.digg),
    # 评论url
    path(r'comment/', views.comment),
    # 评论树url
    path("get_comment_tree/", views.get_coment_tree),

    # 后台管理界面
    # 注册时，上传图片走的路由
    path('upload/', views.upload),
    # 后台管理界面
    re_path(r'cn_backend/$', views.cn_backend),

    # 增
    re_path(r"cn_backend/add_article/$", views.add_article),
    # ajax删除
    path(r"delete_article/", views.delete_article),
    # 编辑
    re_path(r"edit_article/(\d+)/", views.edit_article),
    re_path(r"test/", views.test),

    # 显示当前全网有多少条博客
    path('blog/dashboard/', views.dashboard, name='dashboard'),
    # 写stark 路由

    path('stark/', site.urls),




]

myblog/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from blog import views
from django.views.static import serve
from myblog import settings


urlpatterns = [
    path('admin/', admin.site.urls),


    # 使用include进行urls管理
    path('blog/',include("blog.urls")),
    re_path('', include("blog.urls"))  #

    # path("login/", views.login),
    # path("index/", views.index),
    # re_path('^$', views.index),   #
    # path("register/", views.register),
    # # 修改密码
    # path('change_pwd/',views.change_pwd),
    #
    # # 账户注销
    # path("logout/", views.logout),
    #
    # # media 配置
    # re_path(r"media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    #
    # # 个人站点url
    # # ?P<value1>为组名，可根据组名定位匹配值的位置， 注意：是在.group()中的标记
    # #  ?P<value>的意思就是命名一个名字为value的组，匹配规则符合后面的/w+
    # # re_path(r'^test/$',views.test),
    # # re_path(r'^(?P<username>\w+)/$', views.home_site),
    # # 个人站点基于 当前用户的 的站点
    # re_path(r'^(?P<username>\w+)/(?P<condition>tag|category|archive>)/(?P<param>.*)/$', views.home_site),
    # # 文章详情页面的实现 ，登陆用户
    # re_path(r'^(?P<username>\w+)/articles/(?P<article_id>\d+)/$', views.user_article_detail),
    # # 未登录用户
    # re_path(r'^articles/(?P<article_id>\d+)/$', views.article_detail),
    #
    # # 点赞视图url
    # path(r'digg/', views.digg),
    # # 评论url
    # path(r'comment/', views.comment),
    # # 评论树url
    # path("get_comment_tree/", views.get_coment_tree),
    #
    # # 后台管理界面
    # # 文章的增删改查功能url
    # path('upload/',views.upload),
    # # 后台管理界面
    # re_path(r'cn_backend/$',views.cn_backend),
    #
    # # 增
    # re_path(r"cn_backend/add_article/$",views.add_article),
    # # ajax删除
    # path(r"delete_article/",views.delete_article),
    # # 编辑
    # re_path(r"edit_article/(\d+)/",views.edit_article)


]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

'''
    共八张表，到时会生成十张表
    
'''


class UserInfo(AbstractUser):
    '''
    用户信息
    '''

    nid = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to="avatars/", default="/avatars/default.jpg")
    # auto_now无论是你添加还是修改对象，时间为你添加或者修改的时间。
    # auto_now_add为添加时的时间，更新对象时不会有变动。
    create_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    blog = models.OneToOneField("Blog", null=True, on_delete=models.CASCADE, verbose_name="站点对象")

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = "用户信息"

    def __str__(self):  # 当实例对象调用的时候，返回这个改值
        return self.username


class Blog(models.Model):
    '''
    博客信息
    '''
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name="个人博客标题", max_length=64)
    site_name = models.CharField(verbose_name="站点名称", max_length=64)
    theme = models.CharField(verbose_name="博客主题", max_length=32)

    class Meta:
        verbose_name = "博客信息"
        verbose_name_plural = "博客信息"

    def __str__(self):
        return self.title


class Category(models.Model):
    '''
    博主个人文章分类
    '''
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name="分类标题", max_length=32)
    blog = models.ForeignKey(verbose_name="所属博客", to="Blog", to_field='nid', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "博客分类"
        verbose_name_plural = "博客分类"

    def __str__(self):
        return self.title


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)  # primary_key  设置这个键为主键
    title = models.CharField(verbose_name="标题名称", max_length=32)
    blog = models.ForeignKey(verbose_name="所属博客", to="Blog", to_field="nid", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "博客标签"
        verbose_name_plural = "博客标签"

    def __str__(self):
        return self.title


class Article(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name="文章标题")
    desc = models.CharField(max_length=255, verbose_name="文章描述")
    content = models.TextField(verbose_name="文章内容")
    # auto_now_add为添加时的时间，更新对象时不会有变动。
    create_time = models.DateTimeField(verbose_name="文章创建时间", auto_now_add=True)
    comment_count = models.IntegerField(verbose_name="评论数量", default=0)
    up_count = models.IntegerField(verbose_name="点赞数量", default=0)
    down_count = models.IntegerField(verbose_name="下载数量", default=0)

    user = models.ForeignKey(verbose_name="作者", to="UserInfo", to_field="nid", on_delete=models.CASCADE)
    # 文章分类
    category = models.ForeignKey(to="Category", to_field="nid", null=True, on_delete=models.CASCADE)
    # through 用于多对多关系时候，定义中间表，到时会多创建一张表Article2Tag
    # through_fields  用于定义中间表的时候，作为关联两个表的 关联字段
    tags = models.ManyToManyField(to="Tag", through="Article2Tag", through_fields=("article", "tag"))

    class Meta:
        verbose_name = "文章内容"
        verbose_name_plural = "文章内容"

    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name="文章", to="Article", to_field="nid", on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name="标签", to="Tag", to_field="nid", on_delete=models.CASCADE)

    class Meta:
        '''
        unique_together这个选项用于：当你需要通过两个字段保持唯一性时使用。这会在 Django admin
        层和数据库层同时做出限制(也就是相关的 UNIQUE 语句会被包括在 CREATE TABLE 语句中)。
        比如：一个Person的FirstName和LastName两者的组合必须是唯一的，那么需要这样设置：
        unique_together = (("first_name", "last_name"),)
        '''
        unique_together = [
            ('article', "tag")

        ]
        verbose_name = "文章标签"
        verbose_name_plural = "文章标签"

    def __str__(self):
        v = self.article.title + "---" + self.tag.title
        return v


class ArticleUpDown(models.Model):
    '''
    点赞表
    '''
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey("UserInfo", null=True, on_delete=models.CASCADE)
    article = models.ForeignKey("Article", null=True, on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = [
            ("article", "user"),
        ]
        verbose_name = "文章点赞数"
        verbose_name_plural = "文章点赞数"


class Comment(models.Model):
    '''
    评论表
    '''
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name="评论文章", to='Article', to_field="nid", on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name="评论者", to="UserInfo", to_field="nid", on_delete=models.CASCADE)
    content = models.CharField(verbose_name="评论内容", max_length=255)
    create_time = models.DateTimeField(verbose_name="评论创建时间", auto_now_add=True)
    parent_comment = models.ForeignKey("self", verbose_name="父级评论", null=True, on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ("article", "user"),
        ]
        verbose_name = "评论"
        verbose_name_plural = "评论"

    def __str__(self):
        return self.content

templates/article_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>XuMou's Blog&nbsp;|XuMou</title>
    <link rel="stylesheet" href="/static/blog/bs/css/bootstrap.css">
    <link rel="stylesheet" href="/static/blog/bs/css/article_detail.css">
    <link rel="stylesheet" href="/static/blog/bs/css/home_site.css">
    <script src="/static/blog/bs/js/jquery-3.3.1.min.js"></script>
    <script src="/static/blog/bs/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/blog/bs/css/backend.css">
    <style type="text/css">
        * {
            margin: 0;
            padding: 0;
        }

        html, body {
            width: 100%;
            height: 100%;
            background: #f4f4f4;
            margin: 0;
            padding: 0;

        }

        .header {
            width: 100%;
            height: 60px;
        {#background-color: #fff8fd;#} background-color: #fcf8e3;
        }

        .header .title {
            font-size: 18px;
            font-weight: 100;
            line-height: 60px;
            color: white;
            margin-left: 15px;
            margin-top: -10px;

        }

        .backend {
            float: right;
            color: white;
            text-decoration: none;
            font-size: 14px;
            margin-right: 10px;
            margin-top: 10px;
        }

        .pub_info {
            margin-top: 10px;
            color: darkgray;
        }

        /* user_article_detail的样式 */
        .classifications a {
            text-decoration: none;


        }
        .classifications{
            text-align: center;
            margin-left: 74px;
            margin-right: 10px;
            padding: 0;
            margin-top: 20px;

        }


    </style>
</head>
<body>
<div class="header">
    <div class="content col-md-5 col-lg-offset-6">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="/blog/index/">首页</a>
            </li>
            <li>
                <a href="/blog/login/">登陆</a>

            </li>
            <li>
                <a href="/blog/register/">注册</a>

            </li>
        </ul>


    </div>
</div>


<div class="row">
    <div class="col-md-3">
        <div class="classifications">
            <div class="panel panel-warning">
                <div class="panel-heading">标签</div>
                <div class="panel-body">
                    {% for tag in tag_list %}
                        {{ user }}
                        <p><a href="/blog/{{ user }}/tag/{{ tag.0 }}">{{ tag.0 }}({{ tag.1 }})</a></p>

                    {% endfor %}
                </div>
            </div>
            <div class="panel panel-danger">
                <div class="panel-heading">分类</div>
                <div class="panel-body">
                    {% for cate in cate_list %}
                        <p><a href="/blog/{{ user }}/category/{{ cate.0 }}/"> {{ cate.0 }}({{ tag.1 }})</a></p>
                    {% endfor %}

                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">时间归类</div>
                <div class="panel-body">
                    {% for date in date_list %}
                        <p><a href="/blog/{{ user }}/archive/{{ date.0 }}/"> {{ date.0 }}({{ tag.1 }})</a></p>
                    {% endfor %}

                </div>
            </div>


        </div>
    </div>



    <div class="col-md-8">
        <h3 class="text-center"><a href="">{{ article_obj.title }}</a></h3>
        <div class="cont" style="text-indent: 2em;">
            {{ article_obj.content|safe }}
        </div>


        <div id="div_digg">
            {% csrf_token %}
            <div class="diggit action">
                <span class="diggnum" id="digg_count">{{ article_obj.up_count }}</span>
            </div>

            <div class="buryit action">
                <span class="burynum" id="bury_count">{{ article_obj.down_count }}</span>
            </div>
            <div class="clear"></div>
            <div class="diggword" id="digg_tips" style="color: red"></div>
        </div>
        <hr>
        <div class="commonts list-group">
            <p class="tree_btn" style="color: red;font-size: 25px;">评论树</p>
            <div class="comment_tree">


            </div>
            <hr>
            <div class="list-group comment_list">
                <div class="comments">
                    <p>评论列表</p>
                    <ul class="list-group comment_list">
                        {% for comment in comment_list %}
                            <li class="list-group-item">
                                <div>
                                    <a href="">#{{ forloop.counter }}楼</a>&nbsp;&nbsp;
                                    <span>{{ comment.create_time|date:"Y-m-d H:i" }}</span>
                                    <a href=""><span>{{ comment.user.username }}</span></a>
                                    <a class="pull-right reply_btn" username="{{ comment.user.username }}">回复</a>
                                </div>
                                <!-- 判断是否是有父级 pid -->
                                {% if comment.parent_comment_id %}
                                    <div class="pid_info well">
                                        <p>
                                            {{ comment.parent_comment.user.username }}:{{ comment.parent_comment.content }}
                                        </p>

                                    </div>
                                {% endif %}

                                <div class="comment_con">
                                    <p>{{ comment.content }}</p>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>


                <p>发表评论</p>
                <p>
                    <!-- 带有一个禁用输入字段的 HTML 表单： -->
                    昵称:<input typeof="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50"
                              value="{{ username }}">

                </p>
                <p>评论内容</p>
                <textarea name="" id="comment_content" cols="60" rows="10"></textarea>
                <p>
                    <button class="btn btn-default common_btn">提交评论</button>
                </p>
            </div>
        </div>

        <!-- 给点赞图片绑定点赞事件 -->
        <script>
            $("#div_digg .action").click(function () {
                // 检查当前 div是否有 diggit 这个属性 ，有则为true，无则为false
                var is_up = $(this).hasClass("diggit");

                //传入ajax事件
                $.ajax({
                    url: "/blog/digg/",
                    type: "post",
                    data: {
                        "csrfmiddlewaretoken": $("[name = 'csrfmiddlewaretoken']").val(),
                        "is_up": is_up,
                        "article_id": "{{ article_obj.pk }}",
                    },
                    success: function (data) {

                        if (data.state) {
                            if (is_up) {
                                /* parseInt() 函数可解析一个字符串，并返回一个整数。  */
                                var val = parseInt($("#digg_count").text());
                                $("#digg_count").text(val + 1);
                            } else {
                                var val = parseInt($("#bury_count").text());
                                $("#bury_count").text(val + 1);
                            }
                        } else {
                            if (data.handled) {

                                $("#digg_tips").html("您已经推荐过了！");
                            } else {
                                $("#digg_tips").html("您已经反对过了！");
                            }
                            setTimeout(function () {
                                $("#digg_tips").html("")

                            }, 1000)


                        }
                    }
                })
            });

            //评论请求
            var pid = "";
            $(".common_btn").click(function () {
                var content = $("#comment_content").val();
                if (pid) {
                    var index = content.indexOf("\n");
                    content = content.slice(index + 1);
                }
                $.ajax({
                    url: "/blog/comment/",
                    type: "post",
                    data: {
                        "csrfmiddlewaretoken": $("[name = 'csrfmiddlewaretoken']").val(),
                        "content": content,
                        pid: pid,
                        "article_id": "{{ article_obj.pk }}",
                        "user_id": "{{ user.pk }}",
                        "user": "{{ username }}",
                    },
                    success: function (data) {
                        {#console.log("================", data);#}
                        var create_time = data.create_time;
                        var username = data.username;
                        var content = data.content;
                        var s = `
                    <li class="list-group-item">
                    <div>
                        <span>${create_time}</span> &nbsp;&nbsp;
                        <a href=""><span>${username}</span></a>
                    </div>
                    <div class="comment_con">
                        <p>${content}</p>
                    </div>
                </li>`;
                        $("ul.comment_list").append(s);

                        //清空评论框
                        pid = "";
                        $("#comment_content").val("");
                    }

                })

            });
            // 回复评论按钮事件
            // focus()方法 添加函数到 focus 事件。
            // 当 comment_content 字段获得焦点时发生 focus 事件：
            $(".reply_btn").click(function () {
                $("#comment_content").focus();
                var val = "@" + $(this).attr("username") + "\n";
                $("#comment_content").val(val);
                pid = $(this).attr("comment_pk");
            });

            //评论树
            $.ajax({
                url: "/blog/get_comment_tree/",
                type: "get",
                data: {
                    article_id: "{{ article_obj.pk }}"
                },
                success: function (data) {
                    console.log(data);
                    $.each(data, function (index, comment_object) {
                        var pk = comment_object.pk;
                        var content = comment_object.content;
                        var parent_comment_id = comment_object.parent_comment_id;
                        if (!parent_comment_id) {
                            var s = '<div comment_id=' + pk + '><span>' + content + '</span></div>';
                            $(".comment_tree").append(s)

                        } else {
                            $("[comment_id=" + parent_comment_id + "]").append(s);
                        }
                    })
                }
            });


        </script>


    </div>
    <div class="col-md-1" ></div>


</div>
</div>

</body>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>XuMou's Blog&nbsp;|XuMou</title>
    <link rel="stylesheet" href="/static/blog/bs/css/bootstrap.css">
    <link rel="stylesheet" href="/static/blog/bs/css/article_detail.css">
    <link rel="stylesheet" href="/static/blog/bs/css/home_site.css">
    <script src="/static/blog/bs/js/jquery-3.3.1.min.js"></script>
    <script src="/static/blog/bs/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/blog/bs/css/backend.css">
    <style type="text/css">
        * {
            margin: 0;
            padding: 0;
        }

        html, body {
            width: 100%;
            height: 100%;
            background: #f4f4f4;
            margin: 0;
            padding: 0;

        }

        .header {
            width: 100%;
            height: 60px;
            {#background-color: #fff8fd;#}
            background-color: #fcf8e3;
        }

        .header .title {
            font-size: 18px;
            font-weight: 100;
            line-height: 60px;
            color: white;
            margin-left: 15px;
            margin-top: -10px;

        }

        .backend {
            float: right;
            color: white;
            text-decoration: none;
            font-size: 14px;
            margin-right: 10px;
            margin-top: 10px;
        }

        .pub_info {
            margin-top: 10px;
            color: darkgray;
        }
        /* user_article_detail的样式 */
        .classifications a{
            text-decoration: none;

        }

    </style>
</head>
<body>
<div class="header">
    <div class="content col-md-5 col-lg-offset-6">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/blog/index/">首页</a>
                </li>
                <li>
                    <a href="/blog/cn_backend/">我的博客</a>

                </li>
                <li>
                    <a href="/blog/change_pwd/">修改密码</a>

                </li>
                <li>
                    <a href="#">设置</a>

                </li>
                <li>
                    <a href="/blog/logout/">退出</a>
                </li>
            </ul>


    </div>
</div>
<div class="container">
    <div class="row">

        <div class="col-md-3 menu">
            <br>
            {% load my_tags %}
            {% get_classification_style username %}

        </div>
        <div class="col-md-9">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

templates/change_pwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>XuMou's Blog&nbsp;|XuMou</title>
    <link rel="stylesheet" href="/static/blog/bs/css/bootstrap.css">
    <script src="/static/blog/bs/js/jquery-3.3.1.min.js"></script>
    <script src="/static/blog/bs/js/bootstrap.min.js"></script>

    <style>
        html,body{
            background: #f4f4f4;

        }
        .change_pwd {
            text-align: center;
            position: absolute;
            left: 50%;
            top: 50%;
            width: 450px;
            height: 450px;
            transform: translate(-50%, -50%);
            background-color: #73eeff;
        }




    </style>

</head>

<body>


<div class="row change_pwd">


        <h2>修改密码</h2>
        {% if oldpassword_is_wrong %}
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4>错误!</h4>原密码不正确
            </div>
        {% endif %}
        <div class="well">
            <form class="form-horizontal" action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <p class="form-actions">
                    <input type="submit" value="确认修改" class="btn btn-primary">
                </p>
            </form>
        </div>



</div>



</body>
</html>

templates/classification.html
<div class="classifications">
    <div class="panel panel-warning">
        <div class="panel-heading">我的标签</div>
        <div class="panel-body">
            {% for tag in tag_list %}
                {{ user }}
                <p><a href="/blog/{{ user }}/tag/{{ tag.0 }}">{{ tag.0 }}({{ tag.1 }})</a></p>
            {% endfor %}
        </div>
    </div>
    <div class="panel panel-danger">
        <div class="panel-heading">我的分类</div>
        <div class="panel-body">
            {% for cate in cate_list %}
                <p><a href="/blog/{{ user }}/category/{{ cate.0 }}/"> {{ cate.0 }}({{ tag.1 }})</a></p>
            {% endfor %}

        </div>
    </div>
    <div class="panel panel-success">
        <div class="panel-heading">我的时间归档</div>
        <div class="panel-body">
            {% for date in date_list %}
                <p><a href="/blog/{{ user }}/archive/{{ date.0 }}/"> {{ date.0 }}({{ tag.1 }})</a></p>
            {% endfor %}

        </div>
    </div>
</div>

templates/not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>XuMou's Blog&nbsp;|XuMou</title>
</head>
<h1>not_found page</h1>
<body>

</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>XuMou's Blog&nbsp;|XuMou</title>
    <link rel="stylesheet" href="/static/blog/bs/css/bootstrap.css">
    <style>
        html, body {
        {#height: 100%;#} background-color: #f4f4f4;

        }

        h1 {
            text-align: center;
            color: deepskyblue;
            margin-top: 80px;
            margin-bottom: 30px;
            font-size: 28px;
        }

        #avatar {
            display: none;
        }

        .error {
            color: red;

        }

        #avatar_img {
            margin-left: 20px;

        }

        #avatar_img:hover {
            cursor: pointer;

        }
        .reg_to_index{
            font-size: 33px;
        }
        .reg_to_index a{
            text-decoration: none;
        }


    </style>
</head>

<body>
<h1 class="reg_to_index"><a href="/blog/index/">XuMou's&nbsp;Blog</a></h1>
<div class="container register_div">
    <div class="row">
        <div class="col-md-4 col-lg-offset-4">
            <form id="form">
                {% csrf_token %}
                <!-- form渲染 -->
                {% for field in form %}
                    <div class="form-group">
                        <!--Form.auto_id id 和label 的行为使用Form构造函数的auto_id 参数控制。 这个参数必须为True、False 或者一个字符串。
                            默认情况下，auto_id 设置为'id_%s'；
                            auto_id =True ：有lable和id，此时id的值为Form类中的字段名，有空格的会改为_
                            auto_id =False ：没有lable标签和id属性
                        -->
                        <label for="{{ field.auto_id }}">{{ field.label }}</label>
                        {{ field }} <span class="error pull-right"></span>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <label for="avatar">头像
                        <img id="avatar_img" width="60px" src="/static/blog/bs/img/default.jpg" alt="">
                    </label>
                    <input type="file" id="avatar" name="avatar">
                </div>
                <input type="button" class="btn btn-default reg_btn" name="" value="注册"><span class="error"></span>
                &nbsp;已有账号?&nbsp;<a href="/blog/login/" style="display: inline-block;text-decoration:none; color: #5d9cec;">去登陆！</a>

            </form>
        </div>
    </div>

</div>

</body>
<script src="/static/blog/bs/js/jquery-3.3.1.min.js"></script>

<!-- 进行头像预览操作 -->
<script>
    // .change（function）change事件发生时，就运行funct函数
    $("#avatar").change(function () {
        // 获取用户选中的文件
        var file_obj = $(this)[0].files[0];
        /* 获取文件对象的路径 */
        var reader = new FileReader();
        reader.readAsDataURL(file_obj);
        /* 修改img 这个标签的src的属性，也就是改变src这个对象的路径 */
        reader.onload = function () {
            $("#avatar_img").attr("src", reader.result)
            alert(reader.result)
        };

    });
    <!--  基于ajax提交注册信息 -->
    $(".reg_btn").click(function () {
        var formdata = new FormData();
        formdata.append("user", $("#id_user").val());
        formdata.append("pwd", $("#id_pwd").val());
        formdata.append("r_pwd", $("#id_r_pwd").val());
        formdata.append("email", $("#id_email").val());
        formdata.append("avatar", $("#avatar")[0].files[0]);
        formdata.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

        $.ajax({
            url: "/blog/register/",
            type: "post",
            contentType: false, /* contentType 告诉服务器从浏览器提交过来的数据格式。*/
            /*
             processData
            类型：Boolean
            默认值: true。默认情况下，通过data选项传递进来的数据，如果是一个对象(技术上讲只要不是字符串)，都会处理转化成一个查询字符串，
            以配合默认内容类型 “application/x-www-form-urlencoded”。如果要发送 DOM 树信息或其它不希望转换的信息，请设置为 false。
            */
            processData: false,
            data: formdata,
            success: function (data) {
                console.log("1", data);
                console.log("2", data.user);
                if (data.user) {
                    //注册成功！
                    alert("注册成功");
                    console.log("data_user>>>", data.user);
                    location.href = '/blog/index/'
                } else {
                    //注册失败
                    console.log("注册失败");
                    // 清空错误消息提示
                    $("span.error").html("");
                    // has-error是bootstrap中的一个class
                    $(".form-group").removeClass("has-error");
                    // 这里each是遍历这个data.msg 一维数组的每一个二维数组，而field则是每一个元素的下标，
                    // error_list则表这个一维数组的每一个二维数组
                    // 显示提醒的错误信息
                    $.each(data.msg, function (field, error_list) {
                        console.log(">>>", field, error_list);
                        if (field == "__all__") {
                            $("#id_r_pwd").next().html(error_list[0]).parent().addClass("has-error");
                        }
                        $("#id_" + field).next().html(error_list[0]);
                        $("#id_" + field).parent().addClass("has-error");
                    })
                }

            }

        });

    });
</script>
</html>